---
# Setup LAMP Stack
- hosts: hosts
  tasks:
    - name: install lamp stack on Debian/Ubuntu hosts
      become: yes
      become_user: root
      apt:
        pkg:
          - apache2
          - mysql-server
          - php7.4
          - php7.4-mysql
        state: latest
        update_cache: yes
      when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

    - name: install lamp stack on RHEL/CentOS hosts
      become: yes
      become_user: root
      yum:
        pkg:
          - httpd
          - mysql-server
          - php
          - php-mysqlnd
        state: latest
        update_cache: yes
      when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'

    - name: start apache service on Debian/Ubuntu hosts
      become: yes
      become_user: root
      service:
        name: apache2
        state: started
        enabled: yes
      when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

    - name: start apache service on RHEL/CentOS hosts
      become: yes
      become_user: root
      service:
        name: httpd
        state: started
        enabled: yes
      when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'

    - name: start mysql service on Debian/Ubuntu hosts
      become: yes
      become_user: root
      service:
        name: mysql
        state: started
        enabled: yes
      when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

    - name: start mysql service on RHEL/CentOS hosts
      become: yes
      become_user: root
      service:
        name: mysqld
        state: started
        enabled: yes
      when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'

    - name: create target directory
      file: path=/var/www/html state=directory mode=0755

    - name: deploy index.html
      become: yes
      become_user: root
      copy:
        src: index.html
        dest: /var/www/html/index.html

